# Welcome to Jekyll!
#

# Site settings
title: Human Direction
description: |
  Organic RBG
owner: Adam Zhujiang
first_published: 2016
email: adamzhujiang@gmail.com
baseurl: ""
url: http://adamzhujiang.github.io/RBG/
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/<username>
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>

# Build settings
markdown: kramdown
sass:
  sass_dir: css
  style: :compressed
